sudo: required
language: python

env:
    global:
        - DATABASE_USER=travis
        - DATABASE_PASSWORD=travis
    matrix:
        - TEST_DB_ENGINE=mysql
        - TEST_DB_ENGINE=sqlite

services:
    - docker  # TEMPORARY - docker is not working with mysql
    # - mysql

cache:
  directories:
    - node_modules
    - bower_components

python:
    - "3.4"
    - "3.5"

before_install:
    - pip install flake8 isort
    - make flake
    - export RALPH_VERSION=$(cat VERSION)
    - export NEW_TAG=$RALPH_VERSION-snapshot-$(date "+%Y%m%d")-$TRAVIS_BUILD_NUMBER
    - docker run mysql:5.6 -P "3306:3306" -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" -e "MYSQL_DATABASE=ralph_ng" -e "MYSQL_ROOT_PASSWORD=root" -e "MYSQL_USER=travis" -e "MYSQL_PASSWORD=travis"

install:
    # - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
    # - "sudo apt-get autoremove"
    # - "sudo apt-get install libaio1"
    # - "wget -O mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.17-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
    # - "sudo dpkg -i mysql-5.6.14.deb"
    # - "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
    # - "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
    # # some config values were changed since 5.5
    # - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
    # - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
    # - "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
    # - "sudo /etc/init.d/mysql.server start"
    - npm config set python /usr/bin/python2.7
    - npm install
    - make js-hint
    - gulp
    - make install-test
    - pip install coveralls

script:
    - gulp test
    - make coveralls

after_success:
    - coveralls

before_deploy:
    - sudo add-apt-repository -y ppa:spotify-jyrki/dh-virtualenv
    - sudo apt-get update
    - sudo apt-get install -y devscripts python-virtualenv git equivs dh-virtualenv
    - make build-package

deploy:
    # -   provider: script
    #     script: scripts/travis_deploy_docker.sh
    #     on:
    #         branch: ng
    #         python: 3.4
    #         condition: $TEST_DB_ENGINE = mysql
    -   provider: script
        script: scripts/travis_deploy_bintray.sh
        on:
            branch: ng
            python: 3.4
            condition: $TEST_DB_ENGINE = mysql

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/837fe61b536818b676ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
